#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_SYMBOLS 100

typedef struct {
    char name[50];
    char type[10];
} Symbol;

Symbol declared_symbols[MAX_SYMBOLS];
int symbol_count = 0;

// Load declarations from symtab.txt (created by Parser)
void load_declarations() {
    FILE *f = fopen("symtab.txt", "r");
    if (!f) {
        printf("Semantic Error: Could not find 'symtab.txt'. Ensure Phase 2 ran correctly.\n");
        exit(1);
    }
    char name[50], type[10];
    while (fscanf(f, "%s %s", name, type) != EOF) {
        // Simple check for Redeclaration within this pass
        int exists = 0;
        for (int i = 0; i < symbol_count; i++) {
            if (strcmp(declared_symbols[i].name, name) == 0) {
                exists = 1;
                break;
            }
        }
        if (!exists && symbol_count < MAX_SYMBOLS) {
            strcpy(declared_symbols[symbol_count].name, name);
            strcpy(declared_symbols[symbol_count].type, type);
            symbol_count++;
        }
    }
    fclose(f);
}

// Check if a variable exists in the symbol table
int is_declared(char *name) {
    for (int i = 0; i < symbol_count; i++) {
        if (strcmp(declared_symbols[i].name, name) == 0) return 1;
    }
    return 0;
}

int main() {
    printf("\n----- PHASE 3: SEMANTIC ANALYSIS -----\n");
    
    load_declarations();

    // Opening 'usage_log.txt' which was generated by parser.y
    FILE *usage = fopen("usage_log.txt", "r");
    if (!usage) {
        printf("Error: No 'usage_log.txt' found. Ensure Syntax Phase generated it.\n");
        return 1;
    }

    char var_name[50];
    int errors = 0;

    // Read every variable name used in the program
    while (fscanf(usage, "%s", var_name) != EOF) {
        // 1. Skip constants/numbers (check if first char is digit)
        if (var_name[0] >= '0' && var_name[0] <= '9') continue;

        // 2. Check for Undeclared Variables
        if (!is_declared(var_name)) {
            printf("SEMANTIC ERROR: Variable '%s' used but not declared.\n", var_name);
            errors++;
        } else {
            // Optional: Print successful checks for visibility
            printf("Checking '%s'... OK (declared as int)\n", var_name);
        }
    }

    if (errors == 0) {
        printf("\nResult: Semantic Analysis Completed Successfully.\n");
    } else {
        printf("\nResult: Semantic Analysis Failed with %d errors.\n", errors);
        exit(1);
    }

    fclose(usage);
    return 0;
}